import animation from './animation.js';
import fixHeight from './fixHeight.js';
import mobileNav from './mobileNav.js';
import rightNav from './rightNav.js';
import scrollToId from './scrollToId.js';
import productSlider from './productSlider.js';
import categoriesSlider from './categoriesSlider.js';
import initTabs from './initTabs.js';
import modal from './modal.js';
import langDropdown from './langDropdown.js';
import actionsDropdown from './actionsDropdown.js';
import isDropdown from './isDropdown.js';
import loadMore from './loadMore.js';
import placeholder from './placeholder.js';
import validation from './validation.js';
import whySlider from './whySlider.js';
import similarSlider from './similarSlider.js';
import inputFile from './inputFile.js';
import missionSlider from './missionSlider.js';
import missionToggle from './missionToggle.js';
import teamSlider from './teamSlider.js';
import inviteSlider from './inviteSlider.js';
import phoneInput from './phoneInput.js';
import '../sass/main.sass';


fixHeight();
animation();
mobileNav();
rightNav();
scrollToId();
productSlider();
categoriesSlider();
initTabs();
modal();
langDropdown();
actionsDropdown();
isDropdown();
loadMore();
placeholder();
validation();
whySlider();
similarSlider();
inputFile();
missionSlider();
missionToggle();
teamSlider();
inviteSlider();
phoneInput();